### ISSUE TITLE
Switch in Xiaomi IR remote doesn't show up

### ISSUE THREAD

**Issue by kukki** [syssi/chuangmi_ir#10]
chuangmi_ir.py commit version: [c813877](https://github.com/syssi/chuangmi_ir/commit/c8138775ba6fd41dde0be6819d486f1c99b20710)
hass version: 0.63.3

Switch.yaml:
```
- platform: chuangmi_ir
  host: !secret chuangmi_ip
  name: "Xiaomi IR"
  token: !secret chuangmi_key
  switches:
    tv:
      command_on: 'Z6XHAKYBAAAqBQAAnAYAAJsNAAC2Dxxxxxxxxxxxxxxxxx'
      command_off: 'Z6XHAKYBAAAqBQAAnAYAAJsNAAC2Dxxxxxxxxxxxxxxxxx'
```

Issue:
* switch.tv is not shown as an entity in /dev-state list.
* switch.tv is not shown in group.all_switches
* not sure the usage of switch.send_command_<ir_ip> in service list

Observed:
* switch.chuang_mi_ir_switch is shown in group.all_switches
* switch.learn_command_<ir_ip> is shown in service drop-down list
* switch.learn_command_<ir_ip> works and is able to capture IR command string

**Comment by syssi** [comment]
HA 0.63.3 supports the device. The custom component isn't needed anymore:

https://home-assistant.io/components/remote.xiaomi_miio/

**Comment by kukki** [comment]
xiaomi_miio can only use the IR as script command. What I want is a switch. Is there any way to use it as switch with xiaomi_miio?

**Comment by syssi** [comment]
Hmm... good question. :-) I don't know if I'm honest.

**Comment by syssi** [comment]
Let's fix this component! ;-)

**Comment by syssi** [comment]
Please enable the debug output of this component 

```

logger:
  default: warn
  logs:
    custom_components.switch.chuangmi_ir: debug
```
And provide your home-assistant.log. Does it show something about the missing switch?

**Comment by kukki** [comment]
There is no error or warning about missing switch.
There is only one INFO line for custom_components in log:
```
2018-02-23 16:11:31 INFO (Thread-2) [custom_components.switch.chuangmi_ir] Initializing with host 192.168.1.161 (token 34784...)
```
It was odd.
At the meantime, I add `name` attribute to the chuangmi_ir sub-switch. And it appears in the lists mentioned above. So current workaround for me is to just add the name attribute like this:
```
- platform: chuangmi_ir
  host: !secret chuangmi_ip
  name: "Xiaomi IR"
  token: !secret chuangmi_key
  switches:
    tv:
      name: 'TV Power'
      command_on: 'Z6XHAKYBAAAqBQAAnAYAAJsNAAC2Dxxxxxxxxxxxxxxxxx'
      command_off: 'Z6XHAKYBAAAqBQAAnAYAAJsNAAC2Dxxxxxxxxxxxxxxxxx'
```
It appears as `switch.tv_power`
